/**
 * The AI processing contract.
 *
 * The language model must return strict structured JSON matching the Product
 * schema. This module defines that contract with zod, validates the raw LLM
 * reply against it, and converts the validated result into the canonical
 * field_metadata object used everywhere in ProductIQ.
 */
import { z } from "zod";
import type {
  FieldKey,
  FieldMetadata,
  FieldMetadataEntry,
  SourceKind,
} from "./types";
import { FIELD_KEYS } from "./types";
import { formatDimensions, formatWeight } from "./scoring";

const sourceKindSchema = z.enum([
  "original",
  "ai_generated",
  "ai_inferred",
  "unknown",
]);

const fieldMetaSchema = z.object({
  source: sourceKindSchema,
  confidence: z.number().min(0).max(100),
  /** Exact substring of the source text supporting this value, or null. */
  snippet: z.string().nullable(),
  /** Concise user-facing justification for this value. */
  explanation: z.string().nullable(),
});

export const llmResponseSchema = z.object({
  productName: z.string().nullable(),
  category: z.string().nullable(),
  subcategory: z.string().nullable(),
  material: z.string().nullable(),
  dimensions: z
    .object({
      length: z.coerce.number().nullable(),
      width: z.coerce.number().nullable(),
      height: z.coerce.number().nullable(),
      unit: z.string().nullable(),
    })
    .nullable(),
  weight: z
    .object({
      value: z.coerce.number().nullable(),
      unit: z.string().nullable(),
    })
    .nullable(),
  voltageRating: z.string().nullable(),
  certifications: z.array(z.string()),
  otherSpecs: z.record(z.string(), z.string()),
  descriptionShort: z.string().nullable(),
  descriptionDetailed: z.string().nullable(),
  searchKeywords: z.array(z.string()),
  fieldMetadata: z.object({
    productName: fieldMetaSchema,
    category: fieldMetaSchema,
    subcategory: fieldMetaSchema,
    material: fieldMetaSchema,
    dimensions: fieldMetaSchema,
    weight: fieldMetaSchema,
    voltageRating: fieldMetaSchema,
    certifications: fieldMetaSchema,
  }),
  /** Places where the source text states different values for the same field. */
  conflicts: z.array(
    z.object({
      field: z.string(),
      values: z.array(z.string()),
      snippets: z.array(z.string()),
    }),
  ),
});

export type LlmResponse = z.infer<typeof llmResponseSchema>;

const AI_SYSTEM_PROMPT = `You are ProductIQ, an expert industrial product data analyst working for a B2B catalog intelligence platform. You transform raw, incomplete industrial product information into structured, grounded, commerce-ready product data.

AI RELIABILITY RULES (mandatory):
1. Never fabricate a technical specification that is not supported by the provided source data.
2. Every field must be classified exactly as one of: "original", "ai_generated", "ai_inferred", or "unknown".
3. If a value is directly stated in the source text, preserve the original value and set "snippet" to the exact substring of the source text that supports it (verbatim, character-for-character). Do not paraphrase snippets.
4. If a value is inferred (e.g. the category is clear from context but never stated), classify it "ai_inferred" and provide a confidence score (0-100) and a concise explanation.
5. If you cannot reliably determine a value, return null for the value and classify the field "unknown". Never guess.
6. Never present an inferred value as an original manufacturer specification.
7. Commerce copy (description_short, description_detailed, search_keywords) is generated by you — classify those fields' metadata as "ai_generated". Technical specifications (material, dimensions, weight, voltage_rating, certifications) must remain grounded in the supplied information; never invent them.
8. Evidence must come from the supplied source text. Never invent citations, documents, page numbers, URLs, or evidence.
9. If the source text contains conflicting values for the same field (for example two different voltages), list the field in "conflicts" with the differing values and their verbatim snippets, and choose the most plausible value for the field itself with a lower confidence score.

TECHNICAL GUIDANCE:
- Categories come from this fixed taxonomy: Bearings, Electric Motors, Pumps, Valves, Industrial Sensors, Electrical Components, Power Supplies, Pneumatic Components. Choose the closest one.
- Units: keep the units exactly as stated in the source (e.g. "mm", "in", "kg", "lb"). Do not convert. Unit validation happens downstream.
- Dimensions: use numbers only for length/width/height (no units inside the numbers). Set "unit" to the unit stated for the dimensions, or null if unknown.
- Weight: numeric value plus unit (e.g. "kg", "lb", "g"), or null.
- voltage_rating: the string as stated (e.g. "230 V AC").
- other_specs: any other structured specifications found in the text (e.g. "flow_rate", "max_pressure", "rated_current", "protection_class"), as string values.

OUTPUT: Return ONLY a single valid JSON object matching the schema below. No markdown, no commentary, no extra text.

{
  "productName": string|null,
  "category": string|null,
  "subcategory": string|null,
  "material": string|null,
  "dimensions": {"length": number|null, "width": number|null, "height": number|null, "unit": string|null} | null,
  "weight": {"value": number|null, "unit": string|null} | null,
  "voltageRating": string|null,
  "certifications": string[],
  "otherSpecs": {"key": "value"},
  "descriptionShort": string|null,
  "descriptionDetailed": string|null,
  "searchKeywords": string[],
  "fieldMetadata": {
    "productName": {"source": "original"|"ai_generated"|"ai_inferred"|"unknown", "confidence": 0-100, "snippet": string|null, "explanation": string|null},
    "category": {...}, "subcategory": {...}, "material": {...}, "dimensions": {...}, "weight": {...}, "voltageRating": {...}, "certifications": {...}
  },
  "conflicts": [{"field": string, "values": [string], "snippets": [string]}]
}`;

export function buildUserPrompt(rawInputText: string): string {
  return `Here is the raw product information to analyze. It may be messy, incomplete, or contain errors.

<source_text>
${rawInputText}
</source_text>

Analyze this text and return the structured JSON per the schema in your system instructions. Remember: only return JSON.`;
}

export function getAiSystemPrompt(): string {
  return AI_SYSTEM_PROMPT;
}

/** Keys for which "ai_generated" is not an allowed source — a generated value
 *  must never be presented as a manufacturer specification. */
const GROUNDED_KEYS: FieldKey[] = [
  "material",
  "dimensions",
  "weight",
  "voltageRating",
  "certifications",
];

export function buildFieldMetadata(result: LlmResponse): FieldMetadata {
  const mk = (
    key: FieldKey,
    value: string | number | string[] | null,
  ): FieldMetadataEntry => {
    const meta = result.fieldMetadata[key];
    let source: SourceKind = meta.source;
    // Enforce the reliability rules: grounded technical fields can never be
    // "ai_generated"; downgrade to "ai_inferred" so the UI never implies a
    // manufactured spec is an original one.
    if (GROUNDED_KEYS.includes(key) && source === "ai_generated") {
      source = "ai_inferred";
    }
    const empty =
      value === null ||
      (typeof value === "string" && value.trim() === "") ||
      (Array.isArray(value) && value.length === 0);
    if (empty) {
      return {
        value: null,
        source: "unknown",
        confidence: 0,
        sourceTextSnippet: null,
        sourceDocument: null,
        explanation: null,
      };
    }
    return {
      value,
      source,
      confidence: Math.round(meta.confidence),
      sourceTextSnippet: meta.snippet,
      sourceDocument: null,
      explanation: meta.explanation,
    };
  };

  return {
    productName: mk("productName", result.productName),
    category: mk("category", result.category),
    subcategory: mk("subcategory", result.subcategory),
    material: mk("material", result.material),
    dimensions: mk("dimensions", formatDimensions(result.dimensions)),
    weight: mk("weight", formatWeight(result.weight)),
    voltageRating: mk("voltageRating", result.voltageRating),
    certifications: mk("certifications", result.certifications),
  };
}

/** Verifies that every claimed source snippet actually appears verbatim in the
 *  input text. Downgrades fabricated evidence to inference. */
export function verifySnippets(
  metadata: FieldMetadata,
  rawInputText: string,
): FieldMetadata {
  const normalizedRaw = rawInputText.toLowerCase().replace(/\s+/g, " ").trim();
  const next: FieldMetadata = { ...metadata };
  for (const key of FIELD_KEYS) {
    const entry = metadata[key];
    if (!entry.sourceTextSnippet) continue;
    const normalizedSnippet = entry.sourceTextSnippet
      .toLowerCase()
      .replace(/\s+/g, " ")
      .trim();
    if (!normalizedRaw.includes(normalizedSnippet)) {
      next[key] = {
        ...entry,
        sourceTextSnippet: null,
        source: entry.source === "original" ? "ai_inferred" : entry.source,
        confidence: Math.min(entry.confidence, 60),
        explanation:
          "The claimed source excerpt could not be matched verbatim to the input text, so this value is treated as inferred rather than original.",
      };
    }
  }
  return next;
}
